markdown: redcarpet
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 8
paginate_path: page/:num

blog:
    name:                                                Peach Chou
    description:                                         Be happy. No worries. just smile
    title:                                               Peach Chou - Developer
    url:                                                 http://baidu.com/
    duoshuo:                                             2dxgujun
    tongji:                                              2dxgujun
    qiniu:                                               # 七牛云地址
author:
    name:                                                PeachChou
    email:                                               zhoutaolei@gmail.com
    weibo:                                               weibo.com/zhoutaolei
    google-plus:                                         https://plus.google.com/113657331852211913645
    github:                                              https://github.com/PrinceChou
    logo:                                                /res/img/avatar.jpg
    douban:
        name:                                            Blog for Peach
        key:                                             06909fe6854d983013b1dfb38fe8c890