markdown: redcarpet
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 8
paginate_path: page/:num

blog:
    name:                                                Peach Chou
    description:                                         Be happy. No worries. just smile
    title:                                               Peach Chou - Developer
    url:                                                 http://baidu.com/
    duoshuo:                                             2dxgujun
    tongji:                                              2dxgujun
    qiniu:                                               # 七牛云地址
author:
    name:                                                PeachChou
    email:                                               zhoutaolei@gmail.com
    weibo:                                               http://weibo.com/2dxgujun
    google-plus:                                         https://plus.google.com/113657331852211913645
    github:                                              https://github.com/2dxgujun
    logo:                                                /res/img/avatar.jpg
    douban:
        name:                                            db2dxgujun
        key:                                             0f93d5c81935559d2ebb81584ba000d7