markdown: redcarpet
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 8
paginate_path: page/:num

blog:
    name:                                                Peach Chou
    description:                                         Time waits for no one
    title:                                               Peach Chou - Developer
    url:                                                 https://princechou.github.io/
    duoshuo:                                             Peach
    tongji:                                              Peach
    qiniu:                                               # 七牛云地址
author:
    name:                                                PeachChou
    email:                                               zhoutaolei@gmail.com
    weibo:                                               http://weibo.com/zhoutaolei
    google-plus:                                         https://plus.google.com/113657331852211913645
    github:                                              https://github.com/PrinceChou
    logo:                                                /res/img/avatar.jpg
    douban:
        name:                                            db2dxgujun
        key:                                             0f93d5c81935559d2ebb81584ba000d7