markdown: redcarpet
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 8
paginate_path: page/:num
gems: [jekyll-paginate]
blog:
    name:                                                Peach
    description:                                         To the time to life
    title:                                               Peach - Developer
    url:                                                 http://zhaoxiaoying.com/
    duoshuo:                                             Peach
    tongji:                                              2dxgujun
    qiniu:                                               # 七牛云地址
author:
    name:                                                Peach
    email:                                               zhoutaolei@gmail.com
    weibo:                                               http://weibo.com/zhoutaolei
    google-plus:                                         https://plus.google.com/113657331852211913645
    github:                                              https://github.com/PrinceChou
    logo:                                                /res/img/avatar.jpg
    douban:
        name:                                            65822618
        key:                                             06909fe6854d983013b1dfb38fe8c890